// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHnvHmh81qgR4uxhybZ_1Kgwo5SiCzrhs',
    appId: '1:962184695569:web:83816b45ce146aef1ac6b0',
    messagingSenderId: '962184695569',
    projectId: 'mobileprojectapp1111',
    authDomain: 'mobileprojectapp1111.firebaseapp.com',
    storageBucket: 'mobileprojectapp1111.firebasestorage.app',
    measurementId: 'G-66Q9TS9YFT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqJ0EOMDL7aSlHPtWgWVgNAMrdHbhbsNc',
    appId: '1:962184695569:android:3c116124e7ee25dc1ac6b0',
    messagingSenderId: '962184695569',
    projectId: 'mobileprojectapp1111',
    storageBucket: 'mobileprojectapp1111.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwO1iok1QUXxX_1El7i8UcHMXSBJD4Bp0',
    appId: '1:962184695569:ios:250082d61143bf4c1ac6b0',
    messagingSenderId: '962184695569',
    projectId: 'mobileprojectapp1111',
    storageBucket: 'mobileprojectapp1111.firebasestorage.app',
    iosBundleId: 'com.yashashgowda1.worksync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwO1iok1QUXxX_1El7i8UcHMXSBJD4Bp0',
    appId: '1:962184695569:ios:083f5b3f6bf821cc1ac6b0',
    messagingSenderId: '962184695569',
    projectId: 'mobileprojectapp1111',
    storageBucket: 'mobileprojectapp1111.firebasestorage.app',
    iosBundleId: 'com.example.worksync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHnvHmh81qgR4uxhybZ_1Kgwo5SiCzrhs',
    appId: '1:962184695569:web:2e6b463b41944d451ac6b0',
    messagingSenderId: '962184695569',
    projectId: 'mobileprojectapp1111',
    authDomain: 'mobileprojectapp1111.firebaseapp.com',
    storageBucket: 'mobileprojectapp1111.firebasestorage.app',
    measurementId: 'G-LQ9MCC1SGT',
  );
}
